### DISCUSSION TITLE
Issues with Kafka User creation

### DISCUSSION THREAD

**Discussion by malindarathnayake-fts** [banzaicloud/koperator#1078] [Q&A]
Hi Everyone 

We are trying to add a user auth with sasl-plaintext

Following the sample config we applied the following

```
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: example-kafkauser
  namespace: kafka-dev
spec:
  clusterRef:
    name: kafka
  secretName: example-kafkauser-secret
  topicGrants:
    - topicName: test-topic
      accessType: read
    - topicName: test-topic
      accessType: write
```

We see the user created but we cannot locate the generated password for the user, any help or guidance would be appreciated
