### ISSUE TITLE
 Issues with Kafka User creation

### ISSUE THREAD

**Issue by malindarathnayake-fts** [banzaicloud/koperator#1079]
## Description

We are trying to add a user auth with sasl-plaintext set on external listener

Following the sample configuration, we applied the following. Test-topic is created and we can send and get messages from it (tested with Plain TEXT)

```
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: example-kafkauser
  namespace: kafka-dev
spec:
  clusterRef:
    name: kafka
  secretName: example-kafkauser-secret
  topicGrants:
    - topicName: test-topic
      accessType: read
    - topicName: test-topic
      accessType: write
```

https://github.com/banzaicloud/koperator/issues/664

Based on this closed issue, to confirm having SSL enabled is a prerequisite to creating a user?

## Expected Behavior

Password for the user should be stored as a secret in the Namespace

## Actual Behavior

We can see the user but the secret is not being generated

## Affected Version

Please provide the version number where this issue was encountered.

## Steps to Reproduce
Create a user 
```
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: example-kafkauser
  namespace: kafka-dev
spec:
  clusterRef:
    name: kafka
  secretName: example-kafkauser-secret
  topicGrants:
    - topicName: test-topic
      accessType: read
    - topicName: test-topic
      accessType: write
```

## Checklist

- [x] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue
