### ISSUE TITLE
Problem with deletition topics after namespace deleted

### ISSUE THREAD

**Issue by borisputerka** [banzaicloud/koperator#306]
**Describe the bug**
We had a little problem when we deleted namespace with `KafkaTopic` resources. Kafkatopics could not be delete so namespace deletion was stuck on this. Operator gave us this logs
```
{"level":"info","ts":1582284945.63235,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284946.7028763,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284947.678718,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284948.7105887,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284949.759202,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284950.6829805,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284951.9531028,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284952.666466,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284953.6748793,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284954.6526556,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284955.6499674,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"}
{"level":"info","ts":1582284956.698975,"logger":"kafka_util","msg":"Topic MC2-auditlog still going down for deletion"} 
```
After little investigation we find out that when you manually delete single topic that is going to be deleted every topic was deleted afterwards and namespace could  be finally deleted. Its kinda strange behaviour.

**Configuration/process**
In namespace there are 6 topics.
Delete namespace via kubectl
See log above.
Delete one topic manually of kafka via ./kafka-topics
Every topic was deleted afterwards as response to delete namespace and so namespace was

**Comment by borisputerka** [comment]
```
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  annotations:
    app.kubernetes.io/managed-by: ops-kube
  finalizers:
  - finalizer.kafkatopics.kafka.banzaicloud.io
  generation: 1
  labels:
    app: kafka-topic
    kafkaCluster: kafka.gd1
  name: gd1-auditlog
  namespace: gd1
spec:
  clusterRef:
    name: kafka
    namespace: gd1
  config:
    retention.ms: "2592000000"
  name: GD1-auditlog
  partitions: 1
  replicationFactor: 3
status:
  state: created
```

yaml of one of topics
