### ISSUE TITLE
KafkaUser prefixed topicGrants doesn't work

### ISSUE THREAD

**Issue by kevinnoel-be** [banzaicloud/koperator#374]
**Describe the bug**
Creating KafkaTopics starting with a common prefix and creating a KafkaUser with prefixed topic grants doesn't work 

**Steps to reproduce the issue:**
- Apply following manifest containing topics & 
```yaml
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: test-prefix-topic1
spec:
  clusterRef:
    name: kafka
  name: test-prefix-topic1
  partitions: 1
  replicationFactor: 1
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: test-prefix-topic2
spec:
  clusterRef:
    name: kafka
  name: test-prefix-topic2
  partitions: 1
  replicationFactor: 1
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: test-prefix-user
spec:
  clusterRef:
    name: kafka
  secretName: test-prefix-certs
  topicGrants:
  - topicName: test-prefix-
    patternType: prefixed
    accessType: read
  - topicName: test-prefix-
    patternType: prefixed
    accessType: write
```
- Run a test pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-prefix
spec:
  containers:
    - name: test-connection
      image: confluentinc/cp-kafkacat:latest
      volumeMounts:
        - name: kafka-certs
          mountPath: /etc/kafka-certs
          readOnly: true
      command:
        - kafkacat
      args:
        - -b
        - $(KAFKA_BROKER)
        - -L
        - -X
        - security.protocol=ssl
        - -X
        - ssl.key.location=$(KAFKA_CERTS)/tls.key
        - -X
        - ssl.certificate.location=$(KAFKA_CERTS)/tls.crt
        - -X
        - ssl.ca.location=$(KAFKA_CERTS)/ca.crt
      env:
        - name: KAFKA_BROKER
          value: kafka-headless:29092
        - name: KAFKA_CERTS
          value: /etc/kafka-certs
  restartPolicy: Never
  volumes:
    - name: kafka-certs
      secret:
        secretName: test-prefix-certs
```
- Output of the pod is:
```
Metadata for all topics (from broker -1: ssl://kafka-headless:29092/bootstrap):
  3 brokers:
   broker 0 at kafka-0.kafka-headless.svc.cluster.local:29092
   broker 2 at kafka-2.kafka-headless.svc.cluster.local:29092
   broker 1 at kafka-1.kafka-headless.svc.cluster.local:29092
  0 topics:
 stream closed
```

**Expected behavior**
To have access to all topics with the configured prefix `test-prefix-`.

**Screenshots**
N/A

**Additional context**
- Operator version: `0.10.0`
- Defining `literal` topic grants on every topics works, but we don't know those names before-hand
- Kafka cluster relevant configuration:
```
...
  listenersConfig:
    internalListeners:
    - containerPort: 29092
      name: ssl
      type: ssl
      usedForInnerBrokerCommunication: true
  readOnlyConfig: |
    auto.create.topics.enable=false
    authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
    allow.everyone.if.no.acl.found=false
...
```
