### ISSUE TITLE
Failed to list KafkaTopics

### ISSUE THREAD

**Issue by Chivolta** [banzaicloud/koperator#727]
**Describe the bug**
Topic creation does not work in version v0.20.1. In version v.0.20.0 works perfectly. Getting error:
```
admission webhook "kafkatopics.kafka.banzaicloud.io" denied the request: API failure while retrieving KafkaTopic list, please try again
```
Operator manager logs:
```
{"level":"info","ts":"2022-01-03T22:57:40.834Z","logger":"webhooks","msg":"AdmissionReview for Kind=kafka.banzaicloud.io/v1alpha1, Kind=KafkaTopic, Namespace=kafka Name=test-topic UID=5bc73149-b92b-4325-bc88-ad406210e41e patchOperation=CREATE UserInfo={masterclient  [system:masters system:authenticated] map[]}"}
{"level":"info","ts":"2022-01-03T22:57:40.834Z","logger":"webhooks","msg":"Doing pre-admission validation of kafka topic test-topic"}
{"level":"info","ts":"2022-01-03T22:57:40.834Z","logger":"webhooks","msg":"failed to list KafkaTopics"}
```

**Steps to reproduce the issue:**
Create new topic:
```
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka
spec:
  clusterRef:
    name: kafka
  name: test-topic
  partitions: 3
  replicationFactor: 2
  config:
    "retention.ms": "604800000"
    "cleanup.policy": "delete"
```

**Expected behavior**
New topic should be created.

**Screenshots**

**Additional context**
version v0.20.1
