### ISSUE TITLE
serverSSLCertSecret: no certificates found

### ISSUE THREAD

**Issue by lavis11** [banzaicloud/koperator#839]
SSL is enabled for all listeners, used serverSSLCertSecret in CR
kafka-server is the secret under kafka namespace used to refer in serverSSLCertSecret. it has keystore.jks, truststore.jks, password
Yet it throws no certificates found\nfailed to decode certificate Error
![image](https://user-images.githubusercontent.com/109965394/181026980-6d439b10-4535-47e9-b3fa-5645e450aae7.png)

**Comment by bartam1** [comment]
Hello! Thank you for the feedback.
I have found a missing part in our documentation: https://github.com/banzaicloud/koperator/blob/f274c50e1c957c5b11788fe77740de398050b318/api/v1beta1/kafkacluster_types.go#L520.

For internal listener which is used for controller communication or inner broker communication (https://github.com/banzaicloud/koperator/blob/f274c50e1c957c5b11788fe77740de398050b318/api/v1beta1/kafkacluster_types.go#L504) the ServerSSLCertSecret needs to contain the TLS certificate in PEM and base64 encoded form with key: tls.crt
This is needed to get the CN field for kafka ACL.
In the future we should get this information from the JKS certificates. Until this you need to add for this additional data into the referenced kafka-server secret.

**Comment by bartam1** [comment]
I have found another mistake in our documentation.
When custom server cert is used, the client SSL Cert needs to be specified too.
https://github.com/banzaicloud/koperator/blob/f274c50e1c957c5b11788fe77740de398050b318/api/v1beta1/kafkacluster_types.go#L96
This ClientSSLCertSecret has to contain these data fields:
keystore.jks, truststore.jks, password,
 tls.crt, tls.key, ca.crt  in PEM and base64 encoded format

**Comment by lavis11** [comment]
@bartam1 Thanks for your valuable input.

Configured clientSSLCertSecret, serverSSLCertSecret for SSL secrets.
It is working fine kafka is up and running.
But it throws error like 
![image](https://user-images.githubusercontent.com/109965394/181454695-88aa891c-2655-439a-a2de-0a1af8de1c59.png)

Could anyone help to sort it out!

**Comment by bartam1** [comment]
@lavis11 Welcome!
This error can happen when the Koperator cannot connect to the brokers. This can be caused by wrong client certificates.
This can be used to create proper certificates: https://github.com/confluentinc/confluent-platform-security-tools/blob/master/kafka-generate-ssl.sh
The secret should looks like:
```yaml
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lVSHZWbSs2N05vV0I1cXY1RnpKclpnTmxxSDdnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TVRFeE1qVXdPVEl6TXpOYUZ3MHpNVEV4Ck1qTXdPVEl6TXpOYU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRE55R0U3SFRCaFFKUXYwMlFiUWNibUs5ZTlyN2RkR0dxRVQ3QzRGdDV4Clk0eVdPY3lvc1J5dCtiZ1FVajk0aDZjUExBbDA2dXBBSUNBNkhXREVvdkdjL29zQVNxTkYyd3d3c0IvR3dXR2gKVzJQUHZDdWMycXE2bFlJVzhmZU9CblgrdjVrVVdkMWdMVFFacWtRbnhaTnRyeGFBeXZHZSt3ZUpqTWNPeU1CZAowbGZVb0VwcDJIa3p2bnZ3VllaWnhRbkNlL0QyVCsxbXM5WW9MelI4UW82ekNXWUloRHl2Ukdycy9FNk82MCtIClVvemtQRWN1RXNGZ3E3Q2I4YkhFNDFqZkZkb2FSRHk1RUZFNzREV3lwM0hsQWphTldGSHA3U3JLOHYvVGQ0NmIKbEM0WWZEeCsvTk1OOXhLWnJaN2hxTlhBV1M5RnR2SnVNT1QwOERyZ0M3RlRBZ01CQUFHalV6QlJNQjBHQTFVZApEZ1FXQkJTSzV0N0FEMjBKOUpTQUducGNYV0RHdHdGWktUQWZCZ05WSFNNRUdEQVdnQlNLNXQ3QUQyMEo5SlNBCkducGNYV0RHdHdGWktUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmYKTlFYblp0NEFqckJaN0EvTWRXZjFaWGFYNUNqQTU1akc2SklFOEtWL01hRUtsbnhpcFlhdENQUDB2bTRKeEhkTgpGOXhaWmtVd2pQdUNrSjBRK0QxUzhFTVJOOWJMM3pmcTV4MTNLZFpXM1pXcFo4ZWRnUG9oOWNOcUtMbDQwZ1ZBCjU2K25pZWdWdm9TWVZTenViU09KK09HZ3czY0pZcTNFejZ0TzRLSWM0WGhIaGc0Qm5yM1BCdUhnWXQvSzgrTkEKUGo4L2twdXZ5T1NZN3J1a3ZXSXJ6SnJQWDBnTmFWcTJXa0s1Slc0R1VHQjFxR1hnbUtHdFdpOWJicGliZzZ0cAp6SWh5NjNwL000aFdQTHEwQlZWUGEweTkxODEyMC9yWkxsSmtWUFR2d3FFNkwzaEEzQU5nRnppSG1pREViZUNqClZCVWVCT01SbEZwajhtQUxuN3VGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  keystore.jks: MIIRwQIBAzCCEXoGCSqGSIb3DQEHAaCCEWsEghFnMIIRYzCCBW8GCSqGSIb3DQEHAaCCBWAEggVcMIIFWDCCBVQGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBTCxdKNNJ7fR3qEbvuxCheapgCBGwIDAMNQBIIEyGnS0zcQ1ddIka9+InnnT/m7rG2GdjYwg8wuMOmtYFYz1D/pj13Ez1WaWip9EvOGN/cjlqDtzyefr4+h5aEWeWChLtq6rVAGMcc44CKolJEDn4octz8Qu5aAIRy/TcOOPf2tpnALHv/nd+6QCLfVKP3mH8Rj7MNSJBnVAO5oym+HUqwZlnQjpLgZ9ojkws7ig+xv4R++QtfC92jF0HuQnBcxLFp56/RxESetM2AbzfT+JKeU7UmJsIFspZdn1VGej1Qy7FTgSc8zQ2DfFVjCCkbZmouLTqXzotKxOYn+DQP98rVw+nMVIm9QHu3iKeuqztVe3qFo4hrAp+rUURURkG/2a7FHoCd85LjXcKqsfcTzyIIRc2yyJhtp1yMQ14ODERPmoG+GJaWgB+Q8uLttT5gdH3w6FnO3JhYyv0vUDGr+b9X3mn8UbbPlFTJUeltcCMANddq02B6JhLCT4wtNvNkUNeM9nQN+lgavVsnoNv4zIGg5pc5clMN1ynT7DFxOC39jsOCDgc16vUMVowZRwXBkBxiiqpQTir1h6HGHwQYZoK1FroJnUlZUgBGIGIfWGanF5AtULB87zQL6N5e49ztrEaFgfZQGvFWMMR6E5mZfCWK5ptUpQBZOTO5qBoLVAkT0EFRbWLgFOUIL8pjn/1QnYqGgL1ibfUMrY/vosUmmQ6rGNQbebc/tHLzQW/usfsjrPY/Ls1M/GQUTUGrBPGGRkP1/fuvr5GIrP0EqpvSbwtbBfocN5zRo1zV4a9ntLD9hpGycK3fiyHQ9c8vYxVsCB6EoDgjQjLaqlyJi2+kpTGHT+J7coL6aBMOhaTZEVOfus5tnapIXbxQnbGpfwRD7T611Heou7MD87UDzWxmkTf9wqotALKDSYGLCxTl5O52oEqNWshcukEyiZHdK03BANCPk1PLQtKYMcTqy23UyHIecCWTJ7k6PCGLzLAYxXDnJ+YLNZhinT0z/9/zdq5Mer8JV+jN7EFhq8Bu2Mk7Hj4CbL4QoVKRJmBq63W4XLp8UlBnkCzTJ4jaTk9EwbQmB1kD4mFZqAykcQeguJe+VcP65XH6LC/Q4TWbrSEpWZLeKoHptsPOnvoWBpNJMlBmtC/fGNGo1PlvAetHnQ3OU+3X85cC4HYjn6WmVnniydQC2OA1ONXe2chvKHXmQ9BVUkSS6OR/RvWzOpozLACVmQ5Oc+0pts/z8hoQzFd1lL07niSR56c9UpeEelRUcwfZT+eRNnHvL2Jo/dxIpsonwHouECg0ythMLE+TS1oAVLNntgA1x6e7UHDPuOjyMHPUXUbsvJYVJabbEd87jn6IZXsT843SP8wqE9v5Iru9gqIYYllCBHDeeIVx7goS2BXoxZdRV3Ji5Eic78SqcMq+HzYfumMvaNRFSkQEaCPAhvWXuTZLbRBEqU8Y/FrCPvwrSYMFmWRzQbVQ3FVtIzrds1QWq0yBRu9CfyXdR5Z2Lb3PkFUqT0WeNFncTlzEgcwJPObMJ5t6upiWH4p7WrZLYS/AN4V81vbXhEvhv+e1zYNxSqcglRHnOvf743T+vx7fsWv0jnvVGYr1cS3mVlmjDZmVNhljH5OfhbB6sxsRQqEukJFfa8SyZ/PPGEEnHvz7Z9o/GE+g/hDFGMCEGCSqGSIb3DQEJFDEUHhIAbABvAGMAYQBsAGgAbwBzAHQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTYzNzgzNjA0Mzc2NjCCC+wGCSqGSIb3DQEHBqCCC90wggvZAgEAMIIL0gYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUTRQWR7PWJimzDdEcEjeBj/p8e0ICAwDDUICCC5gG50lwiz87V3jkjP6u5R8xJN2qOQJuMcQS0KK4aiz7HEisrsbwtwXScMXC/1Uu9hgTE8zzIwawfhmeLw9C/3lbcX8znqKjBLbIeZcg5GEwkTGkQunTSJF5dhW85rokSBeN1Piu5aLhWZeNJ/C99atNZtKI+ILjM4BboRtwWf98DZkRK/cE82yjTrJprvK/yW52gaNGi4fGKaE5BMKl36+CYZgixIjCMo9TF+znxcPHUm5WU3ayWOUTkpJJCkVUimlLGYd6LW9Kjsc9P/MQnQFLTuF6pfbcV6ciIvIb40dO93LTci1KXp/IiWfql7NZ8D8cbS+tG8/b6/XxYq0m+l2RfWCUZguN9cSsYvFmMc8A5hZJbjLMe5c0+/uWfA3owZyDh0GU8fe/jY29GuVMM8l3fCAe/TbMeGpqmcFhIO9UWC7NEjsAvOxiorLL/EOZPy0IY5ZzH+Yg8mPmPh/mpLtBAHWy1gm0Hvc4kqGn2Yh8O/sVM7EtEgl6cJRWVgObz04ngysHR1bd0ykJCRXwxfcuXAGdevQxCoJNSRHZTNK60eqhMMFAPJMnX7yhiOXbfFDtqffBuQ/1eOV2ddRyotqlMWEIH+AP9GM05TLMYg+Qvc72DpCErcJjWEQl9PwZUkUiMvLjrY8blyT2b9/zT4wb3rJiHqsj9MC9SlPWkMYHoe+t04FrKqrKcYG87YBxh4soamJST/NH7sJFxWFybLHSxLBGv0Hw+jo+0U6gC4xTNpnNKLQv33K6a50Rhb6uO5QWgVbbkOxE7cMte4WP+/Dt6Y/47A1xhGsvQEMqynuUxAYmextR41QlFVpsCbupEJI9HpreqKysqN9YjAGKIRlmiID/gqzVNWezN0kZTOHPww2STvXJaKA8Z2YuGylVFIgUCWIt7Srv1qnqZQAEURra+kCJq5VT7Capl/PdKztaGyptv7SO11IjOe2ZxCShLFIieE0ZL353busOYFwO5NHXiOCnA9nFsj/prADArXYmmNvP8CMN0NhWwEo4qh/zLg6doaQsIgfoVvIy659o1lpmC4+fS7cNYCt0FoEMicKZaSHzRGFEM6k5qz+xB1q+1PqT9uuTjY6WGP/vfaxMtWEfNd7/jRa8C7QUzOfmFA5g0Kbrho2xmptdOquuXZlUNJOw3696AOtRFezArxpjEWB4ihu+rmBeNkZMuAPz5/szVtdr27rQhHuab2G5k0hiTWUDLbWuoy1uU8+yahU3a1AXYuNtst+vL1aB4fF//sorTwqltnZg9Ptf2c2MiyKQ+LmbcLy32tNAzSn6EmG4VOJxb1zQWx86QiXti2xShV9ooE7WhrZMbJJfJW4aZ6MbuQ/b52WPyEhh8HbUfxbmKgNVWjnw5SDMrFV4tWHoK4mArrn2qGEIvUCvVIzHAjkl2qloZwqduf8IfNAbWR3tAJys11uWdfFNrFSmmnjWIxo7gfs5PoLB2FYq30+KUHHz/Ipp9iLMjfBvNKWGdP4n7oPo4bidWX6S9tvjBhqS1Uuw7i0uuWIey1wGiAIw8TBJX6XmnR8Nf+p6Qt1Xic6XqIRPk4FurpQmQvVX71AaBkIPa1Jj6Bo7kff9RSXuCLMIlnFH3YUXWrICDHZTXWlvi//SNQ+LAbr53lQId31TlahfeAKwd8kKMVmTONBGEqpFVJbaAzKKMUMDePrV+NeL14TJnhAMRHBq8dSGT8t/fq0vaTboQT+5P7Zx4ZymO2xm1yUAzapTZbdmJYCYVImFDfYfsRKAcVe83nPmjEOYqNyVAvfCjWkp7YsO0pfDZRp8XKnlg0ToEOaX1TV+QzOguwxy1PXsTrB4LVfmW+jq0CILpYQXj/y4v8L696MYsiMZya6kqWQocw0fyekeSG8B0QX6HQfhOUTDlUAMNgYoZuA6c3aqs85p4bmRIUCmiI18WNJdgXNfSop+KRXBAjmOicvJSvjTdyU0lu/VVtE6VoTbC9OdBFbibG34Pbi43DpfzHqmtYnCCojL7bCd/wZw41segfWp3XnKpDd7SNFA8AkxPsgyauU7SLZJ+9RqNXg7HDIIy6uVumYDZaRzAqG09uiC7lu7wcPFuw/lDx7dN27Mwmbu27VVLFYBqfY/uQonXEAnXe++Vqmwzg5B8iP1Ej/nEoDAhAkcgqsPr1ND+/wZRpbtVsj08opn5UfxVe6Mmuq9ondWQ3fO21Dz8XPEDBlTcOkY70jNArPW8CWzNg2OVx7JII2+IVDa2fJCmpRdh0pMy0UNab4MRtBafW3DJjBOJTZWtCunkPhgVGYXw15sDcTAxfwNhBeG6J77mOtZ6VHeS08PkVXJXc9nbpzwWa6Hl+lza4PLE6W3g+L3iegbAEGFvWe2JDGUy9SSEQ1l798GDd18LKSwisKYW8qURhWz25z4uSGU/XMhSDLoTLFGusA1WSPXIyCPVr7fSZ7XvrptZQJO6YJVIU+Y9mGLwHRzj5WlYeIkNEELAJTP6Ko20tjgH+lCAvNfSy/KRAEVbThH1KZ5cIV+TZrTJXOeupTrp6DJjlFINh8ZnaL+a1yLO4o3jWGo8YM3V7VcJSwKQnqJt55H5kfaBAZqTZ3dwn3MLWWoGp9mzXxttrfxibzQLlWrLskgITFCOQwfUzTNsEHOj1PHg0R5kP4Z+FCX+azPE7VTzXa0jHROYSZK01sYhqL6TIGXFKzAoil6HEgd2Xz9O6ZY5EoA7QW6kz/+YYVoON5ZEQqwbjEpXKwUHEDh4dWdTOFGJ4205cXUsm03oWxi+a45QTztlhQU/bFzg9+WsTYyE3aipaD0apYBU3ce1gAYdJiaFwMhI3ZS2364zx7vHdqzaMyDksjmpilReKekyHqoou/+ZL00uiMCnXGNEavc7M+j1v6LQmNwmJQ6xtbg8EOaIAM/6FIattEv+cB0psKD9xi8L8ASJoicLCtWDnBH93cC/4bcLk0ACbcVfnPD9fy7S88mxt8LUzm7Fh5OLtYcSh9IpzadtaOms0fKCwojCD5aBxj4XbX+qCZWcIyiklPlOtSj3wLSnKRRv+P7j8BmdgA0sIEgD2w83JuXZJ4ZWucRszMisZA3rUsqGSU9PmJQWV+jkkkdGVnM4uOmJqRnK+YQgGtZsGUqwbTuL/rnGrvvpShFlnJoCVUW411h1zdyFtrpCmr3PFHmgQlISJEUQnt4g0+B/MjDX8APUAvRxpBJxbASdRIu/+XZq1JWHstVfJTQ/k3/Fd/QPRXLjB9g8HN4V+teOfnFfuXHIKrRrl3KEm8Tfr3eDiiMfyLnQRLQj8EjuYUUuaNwZFvaaDUfOuj/zILXgJjAJjnpmKGNL/S2owfUGTgQb3UeZXI3xZ7VrEmaN7le1KmOuM2AQbxVKMjAdKnWtQJSpHEtdz1TLSuA8CarbMss0iOoshisAxJ8zJTNLzZfns8tQSTL4xAXPjLoCDy1mL7PxUWdhZarDMmF/kDng52tJK44o5T8kYto0f5BWgQGDuoZwX75qrAbJ7+DfI/j9I2wirNzgWwkPPuKHWJiIel3BRX5UhRqRJDfKnZI3x/AdWoQiY+ik7mquMrp4HH42PK+x9H0ic+ySnFwdQt7+CzsS+GTIGGffnElsZedL73a3yXC3ZLB8l54884EKw05kMZkaRqFsI4Bq0g8hzOMxrt4uvGtLETNm3d7HV4WhFyFVk7/3MU0Bz4HS753XJlYlN43jBv2BiqTBqccDvXvMRUis+ak7dIOKl9RgbrdttkPaDMfpIcUxQ7pQevJT9QFFnzfN1fURvQA4gpkPA7h8ZGqq6+LDN+ViOGoF5caJ+jq4uhi2BP9iAfA+O25gw6KutqFUkh7gdTjbcC1tMJwxZ+kyFVSURycBZ3mk1l+uEj2FHECu7dUNcilA8/n7aGg6O69gRZXPRg9hXw5rl9shnJ79fMI/a6eoR4P5OJjmdjzeY8i0nkjg6+hsCNK6FpNNnwUtutArY3A/NsCC9BhMD4wITAJBgUrDgMCGgUABBRIh/JvekNS17G5b3+S+7ETDS49uAQUlXOM1eR2RNyQxKucD6OeX2XnaAQCAwGGoA==
  password: a29ydGVmYTEyMwo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPVENDQWlFQ0ZINEJJeE15K1FqeTdGUDVKOHN4N1p5aGhWbkJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1FVXgKQ3pBSkJnTlZCQVlUQWtGVk1STXdFUVlEVlFRSURBcFRiMjFsTFZOMFlYUmxNU0V3SHdZRFZRUUtEQmhKYm5SbApjbTVsZENCWGFXUm5hWFJ6SUZCMGVTQk1kR1F3SGhjTk1qRXhNVEkxTVRBeU56RXpXaGNOTWpFeE1USTJNVEF5Ck56RXpXakJ0TVJBd0RnWURWUVFHRXdkVmJtdHViM2R1TVJBd0RnWURWUVFJRXdkVmJtdHViM2R1TVJBd0RnWUQKVlFRSEV3ZFZibXR1YjNkdU1SQXdEZ1lEVlFRS0V3ZFZibXR1YjNkdU1SQXdEZ1lEVlFRTEV3ZFZibXR1YjNkdQpNUkV3RHdZRFZRUURFd2hWYm10dWIzZHVNakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBSXZ3c3NVTDNWcENMZy9kRVhTcG0yakwyMlRsYklQcis1TmJsTllGR2ZzM1R3YWE0UHBXcmFzY2xKSGQKUUZwY2NOMzV5S1g4Wk1vRjUyaDlSTTBQNWtzZnJwUDJEcUU4ejgvMzRBTHZiSXFuMjFrSHVJQXBodEJhRnREVwpCcTY4ZVpKU3llVTJwYldEYVphb2FsMURVNWZWbHdHSTU2MUd4WWZRbTdhU01QOWNCMW05UnljZTR2ZGorNjFQCkoyWERwRzR3M0RtZzJwTUJsVU92WWtjbitjNkRLWWIybC81aGZXRUh0UXMzdURzbHo2ckFlT240dGFydGxhWWEKT3ozcDE5VDAyYXlLQk5yL1lmQ1VjVkFYOGJlOHRzcFNxbHBPSkJLRnp2TW9DZDV5dHg1SGQweTZGSklBNFJ5RwovQW5mK3RqVjF6ZGc5MFc0ZHZaRkhBN2VlV0VDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFzTmtmClVCVFVYOCtRTlNLZDg4OWRuMi9yQldoenNZUTE0bENoNEdaa0Vrb2RWYnZZQUEzUW5PUXFqZnFQN1Y0T3BsWXQKM2k3bjM4ejViemFLUFl5ajArb3llZWdsYkI4ZlZYenNlUThxM2U2em9XajJpMkFUYkJCaldCZlVtMmxWL0RCMgpPWllOLzN1ZmN5eTlXSVhBM0g1UjJ5MEJsMERqVzdTVHZldlZUR3lnR1JvTVpmS2VtNWRkWWZjbXZoYzhuUEJnClVIQXNVa1RVa0ZkVWw1MDBoUGNML1kwTUs0Sk0wUXE0ekdOOWs5bjlFRWJ4T2VoRjNaQXVic1hURllNWFdEaWgKa29PSXVKQm5sQ0FxVzVld0RacEZwdGM5VmM0OC9SV3QzeVozWnhLQml0ZDBMSnh6Q0I1WnZpbnhEb1hEQ01TawpBTjI2cGlzYjlDSDBNSERTVnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ0w4TExGQzkxYVFpNFAKM1JGMHFadG95OXRrNVd5RDYvdVRXNVRXQlJuN04wOEdtdUQ2VnEyckhKU1IzVUJhWEhEZCtjaWwvR1RLQmVkbwpmVVRORCtaTEg2NlQ5ZzZoUE0vUDkrQUM3MnlLcDl0WkI3aUFLWWJRV2hiUTFnYXV2SG1TVXNubE5xVzFnMm1XCnFHcGRRMU9YMVpjQmlPZXRSc1dIMEp1MmtqRC9YQWRadlVjbkh1TDNZL3V0VHlkbHc2UnVNTnc1b05xVEFaVkQKcjJKSEovbk9neW1HOXBmK1lYMWhCN1VMTjdnN0pjK3F3SGpwK0xXcTdaV21HanM5NmRmVTlObXNpZ1RhLzJIdwpsSEZRRi9HM3ZMYktVcXBhVGlRU2hjN3pLQW5lY3JjZVIzZE11aFNTQU9FY2h2d0ozL3JZMWRjM1lQZEZ1SGIyClJSd08zbmxoQWdNQkFBRUNnZ0VBR2d4Z3ltcnQ5Z29SbHVSWWhuVzN0dWNUWEpHVUJHNWRzczArUkNSSTlNa1QKemEvd3BzaVJwU001eUhqOXJKUStjaU0zcFNYNUFOM2VlRVd4RTlhYzBHa0NUd3BqS01Jd0VJOGNSSSthamFpMwpITGhpTUlFS1ZpZ2V6UnE1dmJiWmpsSVl3TERPWVo0bmZtSzFBYzB4ZHpiTDEvNUsyYWN0eDUwZUR2cmhZZmJQCjhLNys0QU15clhRT2hIb2N6dXpPRzh2Yzh0QndKeFV1R01ZTkpPcFpqT2ltT0toZW53aTlrSXdLYjBlSmZhdzIKWkRQclhPZ0IxbTBVc1RXNEp6cjltRVZSSVdMTXZPNnAveTlhNVVYYlprd2lmUlY0bU5hMThMK1gzOEcydWF3bAorTXVFbjZ1RzI4SXlqd1pnd3RZeUhNVlFvcXdHL0JIcnZ1ZEVvWjFTblFLQmdRRHdTVWo5TXovU1ozZnVPQzFyCmFtY0pyaFJsdWk1SFJ3MllTbjhpQlIzUkRSRmVKU1IwKytxelIvd1Q2cFc5N2NFTUhxejgyT0ZidUJYczVqUm8KcGFEVmhZVnJOZVd1VHhXLzV1dUk5cytqMnpwaUg5ZGg1L0h6UXJmNkVmaGJZeVo1N00vQkMzaEd1Tk1BaDRhOQppRVRYTjE4Zko3cUl0VWMvUG1pZG15N3h4d0tCZ1FDVkYzeFY1S0pzY1hwYXpGckVOUlJaNzJSSHI3U29xM2luClZVK2ExTkpaZFFoaDUwWnVmRUZaSmhYcG9BT2w5VGd3anFhWjA5NkhTZTdvajFROVkrY2R1NDIwZEt1NDZRN2MKeDJGNHpHOGlSWWVLSWNpMFhpVVJIVC9xYkptMTF1RmpvN2p5VDV1Y05rbzR4MWlZelRlUW03UnRwYjZIdnB5cApRS1MwSitNN2x3S0JnUURkUFR6ZEZURHdVNkJUVUpwUlNyandhcjRSSkNtMEt6SFRSTlJseUh3NW5XU2VZR2grCjVleWxnZVFSbW02aFg2WGR1T2ppTGZiaGNrK052akFISW1sQjhCeDJLRHdBRUlVZ0draEg1YWd0WUk4VEJlcFUKRlRIckgwVXlGUld0WDA5djk2RWFSNnRJd3FoVTFuUXpVcUsvM2hYUkk4MVdUa0w1Y2tiMHhvdWt4UUtCZ0VhTQpOVzVqWUtRVjBrTFN2Z1JuNVhoaytidWVIY3RPVUNwR0NRUUh2bjFNRHFwZENJdlJTZzdJSWNoSnlsQW1SKzlhCklPVmJSc29YcHUvdW1ucnVJZmVFdnhucnR6SXBQYm9rc2krNTlNQnZ6Q0lGdUhYNHNtdDF2ci9Mb2JSVXVKUXcKYlp4akpRdjIrSW9EY2gzanhXNHM3MlNPOENoRmZ0WHIyOFBQdUF1REFvR0FVcVVISlNzZGFZZjRjTnZxbHRXcwp5RzRiV0Y4U2dCSXV1bEJlS2tuUldtcnNFeTNaWkZyMzF6OFBWK1ZBemkzYmd4cFAxYmVYT3Z1Z0p1Q1VKeHB4CnR6VnZ3YzZxNDJpQ2dydDlDaGttYWdoT0xqaGdVRjJneUxiUXFwRUEyWWoxT1ZJUTVkeEtBNXFYd3VDWFlJTkwKdjZzcThwbWlrcUp6WWVrT0svbkgveUk9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  truststore.jks: MIIEjgIBAzCCBEcGCSqGSIb3DQEHAaCCBDgEggQ0MIIEMDCCBCwGCSqGSIb3DQEHBqCCBB0wggQZAgEAMIIEEgYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQU82EkCNSn+SDx+7vbIdjhQp46WDUCAwDDUICCA9j2tzM7p8Q3P5vpyZMEH6KTftMrVRMH+A4rOi570jZd2/Ue6stoP1cep2t8tbuc98Jq0EdS+/wbAwYbCvssuLzHi4KzGB674sR3avjv7RPeD6Bcx/XbNlNlNIjXLiv0PKB3WWmmZyg8/MysbfDldpUAtGcYSy2xj+q/xyQkSM/Y/tXTFEmCG/7k5ZdzdkhzXX3gReDEDvKS3ueJtnSRedRzP6ZcIes5WfCIrBqhIZOG3U6R/7AdiXDF58b9+Tg+0CqiM/U71kpL9s4/4hXMwKsXq+FFmm1eLrLdhrG/GrrPZceWipg+oQZ/dQlDl+rgbJbhc4cIY02lyyMUDL2YytfDLykRnAN3oL64c01DzhkiZJGT+rtLiow4L/j/ylPEMqvN108z+uFuyXKbgTlq8AnqTT19ViMJZHYr1I6OZJWgkBTwLgwkV1IQYWvy73BR6Rf1MVqkpQZhBzsBWkJReWheHI/3Bz7FOHbn7RJeZAm/ckSV3xjBS6NWsLap4slOXUVtkWUooS00o6Ahj/TVnUScB8BA6/yD1MT3r/QmJyKxQjlbocu5SGWB9DKV/VkqL+3z3aqq2XGEs7IhBsdnLNdGZ0MAzoF289E3Gqhld39YgQfkBDKuwexSmPFqqNKon6W358E545wLbHRiGI1jchHRYh0B6pHxT4il335G6pIMLiCxOqgtaFFe17drc+kjNYdOFygbzdoIWRX8KcRHM8nVrunuNZAVTJimGVqgMzzZbmj4Lf0iky5R28Q6AUvj2v6aMJAxyKCswG0ApC0zmdcTT5Q+RXVnS2V6Asy1UCwjiHv8/5yRuyqcYpjUOTy0v/Sic9BwQ7S0FjCJEFe3tSJ2Kv8K6Y8WvGl9aiD4C50CdE/4kPl4IXk03G7/4isS954DQzhptLRAvJpGonnU76+6B7NxvsY3N3K/a/CZcTBq8o/6vXsErpaP+uHtApvsKPwgLS4Onu2DcSK1q/+2M3wZnRVUIk4irxX+4J6vsUHUhOM1ThTY7QtEetCCSU7T6QiFIMbf/kczO1Uu3xBEg9FqHBtJ4FDEkCjUMQdfyv8bDq4tAtAGQRpS31CGe+TnvoMj2kZdtdbFEw05DUXC5gaI96ylIAyVo+moCASbtzdnNWxtxelYiikj9PTGcctXcu3O/AHu8OqpHzDkMzYImLAVpfBjgAa/A6XtsKrg3ggFQ8vNcratx+mVlrQaGAKeXqrR+QxAVGMBTOv+4A/5Sla/7DvugTGjsvb2mPihmrg7GNDuIXhcAIXtQ42G8Ac0LgQdYkW73QgmJyBjyQDp196q1IwUC5YmRrYwPjAhMAkGBSsOAwIaBQAEFJPdGEre/z+t5I71lMOJztBSviDuBBTFcCaXfLT4FRtj0cK0s12+mqIZqgIDAYag
kind: Secret
metadata:
  name: kafka-server-4
  namespace: kafka
```
