### ISSUE TITLE
Supporting external issuers with custom API groups for cert-manager dependency

### ISSUE THREAD

**Issue by charleenklang** [banzaicloud/koperator#911]
**Is your feature request related to a problem? Please describe.**
The koperator supports the upsteam cert-manager project natively and can use it to create and manage all needed certificates for the kafka brokers and users automatically. However, this functionality currently supports only to define the kind and the name of the issuer, which should be used for the certificate management but not the group.

**Describe the solution you'd like to see**
We would like to use an external issuer with custom API groups for the upstream cert-manager dependency when creating a new kafka cluster or kafka user so that the automatic creation of all needed certificates feature of the koperator can be used.

**Comment by panyuenlau** [comment]
Hey @charleenklang, this feature is now supported by #966  and will be available in the next release

**Comment by panyuenlau** [comment]
Hey @charleenklang, apologies - I think I might've misunderstood this issue, I believe the request is to support users to customize the `issuerRef.group` in two different cases (with cert-manager):

1. `KafkaUser`, for example:
```yaml
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: example-kafkauser-with-pki
  namespace: kafka
spec:
  clusterRef:
    name: kafka
  secretName: example-kafkauser-secret
  pkiBackendSpec:
    pkiBackend: "cert-manager"
    issuerRef:
      name: "ca-issuer"
      kind: "ClusterIssuer"
      group: <supported-group-by-cert-manager>
```
This is already addressed by @shubhamcoc in #966 

2. `KafkaCluster`, e.g.:
```
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
spec:
  listenersConfig:
    internalListeners:
      - type: "ssl"
        name: "ssl"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
        # sslClientAuth defaults to be "required" for two-way SSL authentication, possible values are: "required", "requested", and "none"
        # sslClientAuth: "requested"
      - type: "ssl"
        name: "controller"
        containerPort: 29093
        usedForInnerBrokerCommunication: false
        usedForControllerCommunication: true
        # sslClientAuth defaults to be "required" for two-way SSL authentication, possible values are: "required", "requested", and "none"
        # sslClientAuth: "requested"
    sslSecrets:
      tlsSecretName: "kafka-ca-certs"
      create: true
      issuerRef:
        name: "ca-issuer"
        kind: "ClusterIssuer"
        group: <supported-group-by-cert-manager>
...
```
So the `issuerRef.group` info can be populated into the `Certificate` resource created by the Koperator

And @shubhamcoc is attempting to add this part to #967

---
If this is correct, please reopen the issue since we haven't supported the second scenario to allow users to pass the
