### ISSUE TITLE
Adding a finalizer on a kafkatopics.kafka.banzaicloud.io doesn't prevent the deletion

### ISSUE THREAD

**Issue by cmeichel-scality** [banzaicloud/koperator#953]
**Describe the bug**
Adding a `finalizer` on a `kafkatopics.kafka.banzaicloud.io` doesn't prevent the deletion

**Steps to reproduce the issue:**
1. Prerequisite: have a k8s env ready, and a kafka cluster `my-cluster`
2. create file `topic.yaml`
```yaml
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
    name: my-topic
    finalizers:
        - foo
spec:
    clusterRef:
        name: my-cluster
    name: my-topic
    partitions: 1
    replicationFactor: 1
```
3. Apply is in k8s: `kubectl apply -f topic.yaml`
4. Check the topic is created in kafka (I use https://github.com/birdayz/kaf)
5. Delete the  *kafkatopics.kafka.banzaicloud.io*: `kubeclt delete `: `kubeclt delete kafkatopics.kafka.banzaicloud.io my-topic`
6. Check the topic in kafka => **deleted**
7. check in k8s: `kubectl describe kafkatopics.kafka.banzaicloud.io my-topic` => **still there**

**Expected behavior**
If user add a custom `finalizer`, the topic in kafka should not be deleted. Basically, the topic cannot be deleted since there is still `finalizers` than `finalizer.kafkatopics.kafka.banzaicloud.io`

**Screenshots**
NA

**Additional context**
Basically, the following line (https://github.com/banzaicloud/koperator/blob/master/controllers/kafkatopic_controller.go#L226):
```go
if util.StringSliceContains(topic.GetFinalizers(), topicFinalizer) {
```
should be
```go
if util.StringSliceContains(topic.GetFinalizers(), topicFinalizer) && len(topic.GetFinalizers()) == 1 {
```
