### ISSUE TITLE
does we support to create multiple kafka clusters in the diff namespaces using different koperator ?

### ISSUE THREAD

**Issue by CoffeeHi** [banzaicloud/koperator#986]
Hi, I want to create two kafka clusters in two different namespaces, and two koperator own the two kafka clusters seperately, does it support now ?

**Comment by bartam1** [comment]
Hello @CoffeeHi !
Yes, it is supported. You need to configure Koperator to watch specific namespaces. So every koperator instance will watch different namespaces so you can create as many as you want.
https://github.com/banzaicloud/koperator/blob/3576d6a1f8b5ae2e8351308087bd9aa78906e73d/charts/kafka-operator/values.yaml#L17

**Comment by CoffeeHi** [comment]
Hi @bartam1 thanks for your so quick answer! I'm using supertubes to build my kafka clusters in k8s actually, 
```
apiVersion: supertubes.banzaicloud.io/v1beta1
kind: ApplicationManifest
metadata:
  name: dev-app
  namespace: supertubes
spec:
...
  kafkaOperator:
    enabled: true
    namespace: another-kafka
    valuesOverride: 
...
```
For ApplicationManifest CR, I don't know how I can change the koperator namesapaces parameters inside it, seems it can only add params thru `valuesOverride` right ? I haven't found any more detail descriptions in https://docs.calisti.app/sdm/reference/crd/applicationmanifests.supertubes.banzaicloud.io/ ,
could you provide me a guide ? thanks
